//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lo1ita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<int> Display { get; set; }
        public string Author { get; set; }
        public string CreaterGuid { get; set; }
        public Nullable<int> Hits { get; set; }
        public string Excerpt { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> isDraft { get; set; }
        public Nullable<int> Textlength { get; set; }
    }
}
